server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Redirige todo al index.html para que React maneje el routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Evita cachear el index.html (siempre sirve la versión más reciente)
    location = /index.html {
        add_header Cache-Control "no-cache";
    }
}
